### ISSUE TITLE
ArrayCollection map function in ObjectCollection

### ISSUE THREAD

**Issue by nusje2000** [aeviiq/collection#10]
The object collection inherits a map function from the ArrayCollection. This function returns a static version of itself with the mapped values. When using this method on an ObjectCollection it expects that it can construct the same collection as which the function is called on with the mapped values. This is most likely not possible since the map function is probably used to map values from one thing to another, i.e: from objects to integers.

### Example
```php
class FooCollection extends ObjectCollection {
    protected function allowedInstance(): string
    {
        return Foo::class;
    }
}

class Foo {
    public $id;

    public function __construct(int $fooId) {
        $this->id = $fooId;
    }
}

$collection = new FooCollection(new Foo(1), new Foo(2), new Foo(3));
$collection->map(function (Foo $foo) {
    return $foo->id; // returning the id of foo (integer)
}); // Fails because it cannot construct a FooCollection with an integer array
```

**Comment by aeviiq** [comment]
Fixed in https://github.com/aeviiq/collection/pull/12
