### ISSUE TITLE
Use array<key, value> doc-comments instead of type[] when expecting an array

### ISSUE THREAD

**Issue by nusje2000** [aeviiq/collection#59]
In some cases `Collection|mixed[]` is used to type a parameter to contain either an array or an instance of the Collection class. This however leads to some problems when using PHPStan. When the type[] format is used in combination with a class that implements the IteratorAggregate interface (like the Collection), the type will be parsed to `Collection&iterator<type>`. For more information see https://github.com/phpstan/phpstan/issues/1988. An example of this type definition can be found on `Collection::merge($input)`.

**Comment by aeviiq** [comment]
Solved in https://github.com/aeviiq/collection/pull/60
